# Generated by Django 2.1.7 on 2019-03-11 19:47

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a new version
    # than this migration expects. We use the historical version.
    Person = apps.get_model('core', 'Author')
    for person in Person.objects.all():
        person.name = '%s %s' % (person.first_name, person.last_name)
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
