# Generated by Django 2.1.7 on 2019-03-11 19:47

from django.db import migrations
from django.conf import settings
import os.path
import csv
from django.core.files import File

def load_book_data(apps, schema_editor):
    """
    Read a CSV file full of books and insert them into the database.
    """

    Book = apps.get_model('core', 'Book')
    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'list_of_books.csv')
    with open(datafile) as file:
        reader = csv.DictReader(file)
        for row in reader:
            book_title = row['title']
            if Book.objects.filter(title=book_title).count():
                continue
            book = Book(
                title=row['title'],
                author=row['author'],
                category=row['category'],
                description=row['description'],
                url=row['url'],
            )

            book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_book_data)
    ]
