# Generated by Django 2.1.7 on 2019-03-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190312_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(auto_now=True, max_length=25),
        ),
    ]
